### ISSUE TITLE
Contributor communication channel

### ISSUE THREAD

**Issue by mattfaltyn** [IBM/LNN#47]
Is there a public-facing communication channel (e.g., Slack or Discord) for current and/or potential contributors/researchers? If not, I am happy to set up one! :)

**Comment by NaweedAghmad** [comment]
We've set up a slack channel in the NeSy workspace.
Please send a mail to [Prof Hitzler](hitzler@ksu.edu <hitzler@ksu.edu>) to be added to that workspace
