### ISSUE TITLE
Quickstart instructions update

### ISSUE THREAD

**Issue by tingey** [IBM/LNN#50]
Quickstart instructions 

"3. Install the LNN as a library:  pip install git+https://github.com/IBM/LNN.git"

should be updated to agree with the Box Note instructions;

"3. Install the LNN as a library:  pip install git+https://github.com/GitHubUserName/LNN.git"

**Comment by NaweedAghmad** [comment]
Changing the installation URL is a good idea for those doing the Neuro-Symbolic badge, however, it should remain at the IBM URL in general.

We've included the following instruction as part of the badge instructions to assist:
> Install the LNN as a library, replacing the URL with your forked branch.
