### ISSUE TITLE
Can LNN generates logic rules/hypothesis from the input data (facts)?

### ISSUE THREAD

**Issue by midoriririta** [IBM/LNN#52]
The given examples and tutorial shows LNN can do the logical reasoning from given data and root formulae. 
Can LNN generate logic hypothesis from the given data? Like, can it output the possible logic rules induced from background knowledges? 

Thank you.

**Comment by NaweedAghmad** [comment]
Thank you for the question. 
Inductive logic programming is still an open problem that we and many others are looking at. Please have a look at [the following paper](https://ojs.aaai.org/index.php/AAAI/article/view/20795) to see how LNNs achieves interpretable, state of the art rules induced from data.

**Comment by midoriririta** [comment]
Hi thank you for your reply.
I was wondering if I can find some code of example/demo of how to apply LNN on ilp task (with the induced rules as the output)  in somewhere. It would be nice if you can provide a toy example of it.
Thank you so much!
