### ISSUE TITLE
can't install lnn-contrib

### ISSUE THREAD

**Issue by michalkordyzon** [IBM/LNN#57]
after submitting: 
`pip install -e git+https://github.com/IBM/LNN.git`
I get:
`ERROR: Could not detect requirement name for 'git+https://github.com/IBM/LNN.git', please specify one with #egg=your_package_name`
my environment:
```
Monterey 12.6
Python 3.9.13
setuptools 63.4.1
```

**Comment by NaweedAghmad** [comment]
Append `#egg=lnn` to `pip install -e git+https://github.com/IBM/LNN.git`
`pip install -e git+https://github.com/IBM/LNN#egg=lnn`
