### ISSUE TITLE
Release of semantic parser

### ISSUE THREAD

**Issue by valleballe** [IBM/LNN#61]
Congrats on the work so far! Will the semantic parser specified in your [blogpost](https://towardsdatascience.com/nsqa-neuro-symbolic-question-answering-6d14d98e88f3) be made available?

**Comment by NaweedAghmad** [comment]
Please see the [Neuro-Symbolic Toolkit](https://ibm.github.io/neuro-symbolic-ai/toolkit/) for related open source packages. I believe you are referring to the [AMR-to-Logic](https://github.com/IBM/AMR-CSLogic) component in particular.
