### ISSUE TITLE
Installation on Mac m1

### ISSUE THREAD

**Issue by ismaeelbashir03** [IBM/LNN#70]
I am trying to setup lnn on my Mac, but I get an error when I run the commands in this order below:

brew install graphviz
brew install gmp
env "CFLAGS=-I/usr/local/include -L/usr/local/lib" pip install pycddlib

I have tried installing pycddlib without the flags, but this gives the same error.

The error message:

clang-14: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
      In file included from cdd.c:6:
      /Users/ismaeelbashir/miniforge3/envs/lnn/include/python3.9/Python.h:25:10: fatal error: 'stdio.h' file not found
      #include <stdio.h>
               ^~~~~~~~~
      1 error generated.
      error: command '/Users/ismaeelbashir/miniforge3/envs/lnn/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycddlib

**Comment by NaweedAghmad** [comment]
pycddlib has been removed as a dependency
