### ISSUE TITLE
ERROR: Failed building wheel for pycddlib

### ISSUE THREAD

**Issue by prasannavj** [IBM/LNN#76]
While pip installing the LNN getting the error as below. using fresh docker anaconda environment for the installation.

This has been the case when installing on a normal mode as well. please fix the build file.

and all the documentation link were broken.

**Comment by Mewral** [comment]
Hi, I had the same issue and solved it by apt install libgmp3-dev. Hope it helps

**Comment by NaweedAghmad** [comment]
the requirement for `libgmp3-dev` and `pycddlib` has been removed
